# -*- coding: utf-8 -*-
"""hierarchicalassignmentnm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P0QDob5KTKKlrYECl6S0cTzY-Prkt3Ib
"""

#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# import hierarchical clustering libraries
import scipy.cluster.hierarchy as sch # to build dendrogram and build the plotting
from sklearn.cluster import AgglomerativeClustering

#import data set
Airline=pd.read_csv("/content/EastWestAirlines (1).csv")

Airline.head() #Shows first 5 values

Airline.tail() #Shows Last 5 values

Airline.info()

Airline1=Airline.drop(["ID#"],axis=1)
Airline1

# Normalize heterogenous numerical data using z-score (x-mean/std) or custom defined function
# Normalization function - here custom defined
def norm_func(i): # function name is norm_func, we can give any name here.
    x = (i-i.min())/(i.max()-i.min()) # (Xi-min)/range (Feature Scaling), Range=max-min
    return x

# Normalized data frame (considering the numerical part of data)
Airline1_norm=norm_func(Airline1)

Airline1

#Create Dendograms
plt.figure(figsize=(10,7))
dendrogram = sch.dendrogram(sch.linkage(Airline1_norm, method='complete'))

#Create Cluster (y)
hc=AgglomerativeClustering(n_clusters=5,affinity='euclidean',linkage='ward')
hc

y=pd.DataFrame(hc.fit_predict(Airline1_norm),columns=['clustersid'])
y['clustersid'].value_counts()

# Adding clusters to dataset
Airline1['clustersid']=hc.labels_
Airline1

Airline1.groupby('clustersid').agg(['mean']).reset_index()

#plot Clusters
plt.figure(figsize=(10,7))
plt.scatter(Airline1['clustersid'],Airline1['Balance'],c=hc.labels_)